<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250201145906 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE form_tags (tag_id INT NOT NULL, form_id INT NOT NULL, PRIMARY KEY(tag_id, form_id))');
        $this->addSql('CREATE INDEX IDX_FB9D9031BAD26311 ON form_tags (tag_id)');
        $this->addSql('CREATE INDEX IDX_FB9D90315FF69B7D ON form_tags (form_id)');
        $this->addSql('ALTER TABLE form_tags ADD CONSTRAINT FK_FB9D9031BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_tags ADD CONSTRAINT FK_FB9D90315FF69B7D FOREIGN KEY (form_id) REFERENCES form (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE greeting');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE greeting (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE form_tags DROP CONSTRAINT FK_FB9D9031BAD26311');
        $this->addSql('ALTER TABLE form_tags DROP CONSTRAINT FK_FB9D90315FF69B7D');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE form_tags');
    }
}
