<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250202095613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE element (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, question_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41405E391E27F6BF ON element (question_id)');
        $this->addSql('CREATE TABLE element_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE element_attribute_element (element_attribute_id INT NOT NULL, element_id INT NOT NULL, PRIMARY KEY(element_attribute_id, element_id))');
        $this->addSql('CREATE INDEX IDX_DBD21FA81E2B57F7 ON element_attribute_element (element_attribute_id)');
        $this->addSql('CREATE INDEX IDX_DBD21FA81F1F2A24 ON element_attribute_element (element_id)');
        $this->addSql('CREATE TABLE element_child (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, element_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E69120B01F1F2A24 ON element_child (element_id)');
        $this->addSql('CREATE TABLE image_field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_url VARCHAR(255) NOT NULL, "order" INT NOT NULL, form_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4CB0C1F15FF69B7D ON image_field (form_id)');
        $this->addSql('CREATE TABLE question (id INT NOT NULL, text TEXT DEFAULT NULL, description TEXT DEFAULT NULL, required BOOLEAN NOT NULL, "order" INT NOT NULL, form_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B6F7494E5FF69B7D ON question (form_id)');
        $this->addSql('CREATE TABLE text_field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, "order" INT NOT NULL, form_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D41FF055FF69B7D ON text_field (form_id)');
        $this->addSql('CREATE TABLE topic (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E391E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_attribute_element ADD CONSTRAINT FK_DBD21FA81E2B57F7 FOREIGN KEY (element_attribute_id) REFERENCES element_attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_attribute_element ADD CONSTRAINT FK_DBD21FA81F1F2A24 FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_child ADD CONSTRAINT FK_E69120B01F1F2A24 FOREIGN KEY (element_id) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE image_field ADD CONSTRAINT FK_4CB0C1F15FF69B7D FOREIGN KEY (form_id) REFERENCES form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E5FF69B7D FOREIGN KEY (form_id) REFERENCES form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE text_field ADD CONSTRAINT FK_D41FF055FF69B7D FOREIGN KEY (form_id) REFERENCES form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form ADD topic_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4F1F55203D FOREIGN KEY (topic_id) REFERENCES topic (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5288FD4F1F55203D ON form (topic_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE element DROP CONSTRAINT FK_41405E391E27F6BF');
        $this->addSql('ALTER TABLE element_attribute_element DROP CONSTRAINT FK_DBD21FA81E2B57F7');
        $this->addSql('ALTER TABLE element_attribute_element DROP CONSTRAINT FK_DBD21FA81F1F2A24');
        $this->addSql('ALTER TABLE element_child DROP CONSTRAINT FK_E69120B01F1F2A24');
        $this->addSql('ALTER TABLE image_field DROP CONSTRAINT FK_4CB0C1F15FF69B7D');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E5FF69B7D');
        $this->addSql('ALTER TABLE text_field DROP CONSTRAINT FK_D41FF055FF69B7D');
        $this->addSql('DROP TABLE element');
        $this->addSql('DROP TABLE element_attribute');
        $this->addSql('DROP TABLE element_attribute_element');
        $this->addSql('DROP TABLE element_child');
        $this->addSql('DROP TABLE image_field');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE text_field');
        $this->addSql('DROP TABLE topic');
        $this->addSql('ALTER TABLE form DROP CONSTRAINT FK_5288FD4F1F55203D');
        $this->addSql('DROP INDEX IDX_5288FD4F1F55203D');
        $this->addSql('ALTER TABLE form DROP topic_id');
    }
}
